# Generated by Django 3.2.7 on 2021-10-01 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='JobConfig',
            new_name='Job',
        ),
    ]
